version = 0.1
[default]
[default.pipeline_bootstrap]
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::482791451239:user/aws-sam-cli-managed-dev-env-pipeline-PipelineUser-1EHHRNJU230V3"

[dev_env]
[dev_env.pipeline_bootstrap]
[dev_env.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::482791451239:role/aws-sam-cli-managed-dev-env-PipelineExecutionRole-1P5B2LOHLXI6U"
cloudformation_execution_role = "arn:aws:iam::482791451239:role/aws-sam-cli-managed-dev-e-CloudFormationExecutionR-KPXZCNJZ9EWD"
artifacts_bucket = "aws-sam-cli-managed-dev-env-pipel-artifactsbucket-1nty3ie9ws4ic"
image_repository = ""
region = "us-east-1"

[prod_env]
[prod_env.pipeline_bootstrap]
[prod_env.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::482791451239:role/aws-sam-cli-managed-prod-env-PipelineExecutionRole-TQT83MMJH3X9"
cloudformation_execution_role = "arn:aws:iam::482791451239:role/aws-sam-cli-managed-prod-CloudFormationExecutionR-AXQQOF5WM12H"
artifacts_bucket = "aws-sam-cli-managed-prod-env-pipe-artifactsbucket-bwcdt4ktn5s9"
image_repository = ""
region = "us-east-1"
